### ISSUE TITLE
关于论文中SSv2数据集汇报精度的问题

### ISSUE THREAD

**Issue by wnzhyee** [ruiwang2021/mvd#4]
作者你好，我注意到你在DATASET.md中提到SSv2使用的测试和验证集是相同的，请问下你论文中的精度的测试方式是和VideoMAE中保持一致的吗？但是VideoMAE作者在其repo中提供的test和val split实际上都是SSv2官方提供的验证集（一共24777个样本），官方测试集则是另外一个有着27157个样本的版本。所以我现在有些困惑，实际论文中MVD，VideoMAE以及之前的方法使用的测试集是一致的吗？是都采用的SSv2官方验证集还是测试集呢？期待你的回复，谢谢！

**Comment by xyzforever** [comment]
你好，是一致的

**Comment by xyzforever** [comment]
你好，是一致的
