### ISSUE TITLE
关于SSV2预训练模型

### ISSUE THREAD

**Issue by Wickked-swag** [ruiwang2021/mvd#7]
作者你好，
        我这里想使用一下你在SSV2数据集上的预训练模型，请问是否方便提供一下？

**Comment by xyzforever** [comment]
Hello, our models are first pretrained on Kinetics-400 dataset, then finetuned on downstream video tasks. We have not performed MVD pretraining on other datasets. If you want to perform MVD pretraining on SSv2, you can change the dataset to SSv2 in the code of pretraining and perform pretraining by yourself.
